### ISSUE TITLE
Use go-apk tarball reading/writing instead of current implementation

### ISSUE THREAD

**Issue by kaniini** [chainguard-dev/kontext#8]
Currently `kontext` can only store regular files.  The wolfi build system needs to be able to store symlinks as well.

Using the `go-apk` tarball reading/writing will allow for symlinks and other POSIX filesystem objects to be stored as needed.

**Comment by joshrwolf** [comment]
picking this up since I hit this while iterating on https://github.com/chainguard-dev/melange/pull/464
